### ISSUE TITLE
Dashboard links shouldn't show URL by default

### ISSUE THREAD

**Issue by YairMarcowMavenomics** [Mavenomics/MavenWorks#67]
Looks like this may have gotten broken accidentally since build 822.

http://ec2test.mavenomics.com:7070/822/?src:url=demos/Fund%20Summary%20Ticking.dashboard

**Comment by quigleyj-mavenomics** [comment]
This is the culprit (part of the changeset in #822): https://github.com/Mavenomics/MavenWorks/commit/6d35bf148957636cdfc0a5e7f9367b2ed6ceae8f

Specifically, this line should've changed but didn't (probably because I missed it): 

https://github.com/Mavenomics/MavenWorks/blob/6d35bf148957636cdfc0a5e7f9367b2ed6ceae8f/packages/chart-parts/src/grid/Formatters.ts#L239

```diff
- }, true)
+ }, false);
```

The same change should also be made to the Row Detail Formatter (https://github.com/Mavenomics/MavenWorks/blob/6d35bf148957636cdfc0a5e7f9367b2ed6ceae8f/packages/chart-parts/src/grid/Formatters.ts#L214) and the Table Hover formatter (https://github.com/Mavenomics/MavenWorks/blob/6d35bf148957636cdfc0a5e7f9367b2ed6ceae8f/packages/chart-parts/src/grid/Formatters.ts#L248)
